steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/global-cloud-runtime/vllm-tpu-patched:nightly-20260824-p6', '.']
images: ['gcr.io/global-cloud-runtime/vllm-tpu-patched:nightly-20260824-p6']
timeout: 3600s
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 200
